theme = "gruvbox"

[editor]
line-number = "relative"
mouse = false
rulers = [80]
auto-pairs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
